### ISSUE TITLE
NPE on server

### ISSUE THREAD

**Issue by jottyfan** [noriokun4649/TorchBowMod#2]
Found this NPE in my server logs:

```java
java.lang.NullPointerException: null                                                                                                           
        at mod.torchbowmod.TorchBow.func_77615_a(TorchBow.java:78) ~[?:1.3] {}                                                                
        at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:423) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}               
```

Forge version: 1.14.3-27.0.15
Torchbow version: 1.3

**Comment by noriokun4649** [comment]
I know this issue.
It has already been fixed by commit # 1.
Thank you.
