### ISSUE TITLE
[1.15.2] server crash when fire the 9 torch object

### ISSUE THREAD

**Issue by bloodyraoul** [noriokun4649/TorchBowMod#3]
Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:329) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} to down on Block{minecraft:wall_torch}, it is not an allowed value
	at net.minecraft.state.StateHolder.func_206870_a(SourceFile:112) ~[?:?]
	at mod.torchbowmod.EntityTorch.func_184549_a(EntityTorch.java:104) ~[?:1.2]
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:222) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?]

**Comment by noriokun4649** [comment]
Thank you very much.
This has now been fixed.
