### ISSUE TITLE
Compatibility issue with Torch Slabs Mod

### ISSUE THREAD

**Issue by hjpoe** [noriokun4649/TorchBowMod#7]
**Describe the bug**
Hello! I really enjoy playing with your mod. I think it is very useful and helpful, and it makes sense to have in the game.  

I've been looking through my latest error log from my singleplayer world just now because I am having an (unrelated) crash, and I noticed a lot of exceptions thrown by your mod because of Torch Slabs Mod, and I thought you should know. I have many other mods in this pack, and haven't tested with just this mod and Torch Slabs Mod. 

**To Reproduce**
I looked through the latest.log and noticed a lot of exceptions from unrecognized things from Torch Slabs Mod. 

**Expected behavior**
I expected not to see so many errors between two mods that might be commonly used together.

**Screenshots**
<details>
    <summary>An example of one of the exceptions (they all look like this with different names):</summary>

    [10Jan2021 15:46:41.086] [Render thread/ERROR] [net.minecraft.loot.LootTableManager/]: Couldn't parse loot table torchslabmod:blocks/pad_olive_candle
java.lang.IllegalArgumentException: Can't find block torchslabmod:pad_olive_candle
	at net.minecraft.loot.conditions.BlockStateProperty$Serializer.func_227569_a_(SourceFile:79) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_242]
	at net.minecraft.loot.conditions.BlockStateProperty$Serializer.func_230423_a_(SourceFile:79) ~[?:?]
	at net.minecraft.loot.conditions.BlockStateProperty$Serializer.func_230423_a_(SourceFile:68) ~[?:?]
	at net.minecraft.loot.LootTypesManager$Serializer.deserialize(SourceFile:83) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?]
	at net.minecraft.util.JSONUtils.func_188177_a(SourceFile:456) ~[?:?]
	at net.minecraft.loot.LootFunction$Serializer.func_230423_a_(SourceFile:98) ~[?:?]
	at net.minecraft.loot.LootFunction$Serializer.func_230423_a_(SourceFile:88) ~[?:?]
	at net.minecraft.loot.LootTypesManager$Serializer.deserialize(SourceFile:83) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?]
	at net.minecraft.util.JSONUtils.func_188177_a(SourceFile:456) ~[?:?]
	at net.minecraft.loot.StandaloneLootEntry$Serializer.func_230421_b_(SourceFile:149) ~[?:?]
	at net.minecraft.loot.StandaloneLootEntry$Serializer.func_230421_b_(SourceFile:129) ~[?:?]
	at net.minecraft.loot.LootEntry$Serializer.func_230423_a_(SourceFile:86) ~[?:?]
	at net.minecraft.loot.LootEntry$Serializer.func_230423_a_(SourceFile:74) ~[?:?]
	at net.minecraft.loot.LootTypesManager$Serializer.deserialize(SourceFile:83) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?]
	at net.minecraft.util.JSONUtils.func_188174_a(SourceFile:448) ~[?:?]
	at net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:183) ~[?:?]
	at net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:180) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?]
	at net.minecraft.util.JSONUtils.func_188177_a(SourceFile:456) ~[?:?]
	at net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:245) ~[?:?]
	at net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:242) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[gson-2.8.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:828) ~[forge:?]
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_242]
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38) ~[?:?]
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16) ~[?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_242]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at jeresources.util.LootTableHelper.getManager(LootTableHelper.java:173) ~[jeresources:0.12.0.100]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:51) ~[jeresources:0.12.0.100]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:35) ~[jeresources:0.12.0.100]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) ~[jeresources:0.12.0.100]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[jeresources:0.12.0.100]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:71) ~[jeresources:0.12.0.100]
	at mezz.jei.load.PluginLoader.lambda$new$2(PluginLoader.java:106) ~[jei:7.6.0.51]
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) ~[jei:7.6.0.51]
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:106) ~[jei:7.6.0.51]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:68) ~[jei:7.6.0.51]
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:120) ~[jei:7.6.0.51]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$1(ClientLifecycleHandler.java:97) ~[jei:7.6.0.51]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:692) ~[forge:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1314) ~[?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) ~[?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.42.jar:34.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
</details>

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome

**Additional context**
Minecraft version: 1.16.3
Forge version: 34.1.42
Torch Bow Mod Version: 1.4
Torch Slab Mod Version: 1.6.18

**Comment by noriokun4649** [comment]
I don't understand the relationship.
Looking at the stack trace, I'm guessing that there is a problem with the Loot Table that Torch Slabs Mod rewrote.
My mod don't do anything with the Loot Table, so I don't think it could be the cause of these mods crashing.

**Comment by hjpoe** [comment]
Hmm, I thought I saw your mod in that stacktrace, I guess I misread. My mistake, I'm sorry to bother you.

**Comment by noriokun4649** [comment]
np
Logs starting with "at mod.torchbowmod" are crashing due to my mod.

**Comment by hjpoe** [comment]
Ok, good to know if I find anything in the future.
